import type { Metadata } from "next";

import "./globals.css";
import { BoardProvider } from "@/lib/context/BoardContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Navbar } from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import SessionWrapper from "@/components/SessionWrapper";
import { getServerSession } from "next-auth";
import SignIn from "@/components/SignIn";
import { authOptions } from "@/lib/authOptions";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const boards = await prisma.board.findMany({
    where: {
      ownerId: session?.user.id,
    },
    include: {
      columns: {
        include: {
          tasks: {
            include: {
              subtasks: true,
            },
          },
        },
      },
    },
  });
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-jakarta">
        <SessionWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <BoardProvider initialBoards={boards}>
              {session ? (
                <div className="flex">
                  <Sidebar boards={boards} />
                  <main className="w-full">
                    <Navbar boards={boards} />
                    {children}
                  </main>
                </div>
              ) : (
                <SignIn />
              )}
            </BoardProvider>
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
