import type { Metadata } from "next";

import "./globals.css";
import { BoardProvider } from "@/lib/context/BoardContext";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Navbar } from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import SessionWrapper from "@/components/SessionWrapper";
import { getServerSession } from "next-auth";
import SignIn from "@/components/SignIn";
import { authOptions } from "@/lib/authOptions";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-jakarta">
        <SessionWrapper>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <BoardProvider>
              {session ? (
                <div className="flex">
                  <Sidebar />
                  <main className="w-full">
                    <Navbar />
                    {children}
                  </main>
                </div>
              ) : (
                <SignIn />
              )}
            </BoardProvider>
          </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
